# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Traitement_alfi
                                 A QGIS plugin
 Traitement ALFI 2022
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-07
        copyright            : (C) 2022 by Marc Yeranosyan
        email                : m.yeranosyan@survey-groupe.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Traitement_alfi class from file Traitement_alfi.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Traitement_ALFI_2022 import Traitement_alfi
    return Traitement_alfi(iface)
